# Generated by Django 5.0.6 on 2024-06-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actuators',
            new_name='Actuator',
        ),
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
    ]
