# Generated by Django 5.0.6 on 2024-06-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_actuators_actuator_rename_alerts_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='led1',
            new_name='led_light1_status',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='led2',
            new_name='led_light2_status',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='servo',
            new_name='servo_motor_status',
        ),
    ]
