# Generated by Django 5.0.6 on 2024-06-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_led1_sensordata_led_light1_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
